---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-test
  annotations:
    flux.weave.works/automated: "true"
  namespace: jenkins
  labels:
    app: jenkins-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: itom-devops-dockertest.svsartifactory.swinfra.net/hack-fest19/hackfest-jenkins/jenkins:2.60.3
        env:
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins"
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            memory: 12Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-svc
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-test
  ports:
  - name: http
    port: 36001
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
