apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: busybox
      image: busybox:1.25
      command:
        - /bin/sh
        - -ec
        - |
          echo "Hello-World"
